version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - webnet
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    environment:
      - DEFAULT_EMAIL=enajjachi.zakariaa@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    networks:
      - webnet
    restart: always

  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=paletui.com,www.paletui.com
      - LETSENCRYPT_HOST=paletui.com,www.paletui.com
      - LETSENCRYPT_EMAIL=enajjachi.zakariaa@gmail.com
    expose:
      - "3000"
    networks:
      - webnet
    restart: always

networks:
  webnet:
